server:
  port: 8082

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vermeg_sirh
    username: vermeg
    password: vermeg123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/vermeg-sirh}
  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:vermeg-sirh}
    token-url: ${KEYCLOAK_TOKEN_URL:http://localhost:8080/realms/vermeg-sirh/protocol/openid-connect/token}
    admin-user: ${KEYCLOAK_ADMIN_USER:admin}
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

springdoc:
  swagger-ui:
    path: /swagger-ui.html