server:
  port: 8083
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB

spring:
  application:
    name: recruitment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vermeg_sirh
    username: vermeg
    password: vermeg123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/vermeg-sirh}
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  employee-service-url: ${EMPLOYEE_SERVICE_URL:http://employee-service:8082}
