apiVersion: v1
kind: Service
metadata:
  name: approval-service
  namespace: vermeg
spec:
  selector:
    app: approval-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-service
  namespace: vermeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-service
  template:
    metadata:
      labels:
        app: approval-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done
        - name: wait-for-keycloak
          image: busybox:1.36
          command:
            - sh
            - -c
            - until wget -q -O - http://keycloak:8080/realms/vermeg-sirh/.well-known/openid-configuration >/dev/null; do echo waiting for keycloak oidc; sleep 5; done
      containers:
        - name: approval-service
          image: docker.io/2025omar/vermeg-approval-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              name: http
          envFrom:
            - configMapRef:
                name: vermeg-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vermeg-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
