apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vermeg
configMapGenerator:
  - name: keycloak-realm-import
    files:
      - realm-vermeg.json=keycloak-realm.json
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - keycloak.yaml
  - employee-service.yaml
  - recruitment-service.yaml
  - approval-service.yaml
  - api-gateway.yaml
  - frontend.yaml
