apiVersion: v1
kind: Secret
metadata:
  name: vermeg-secrets
  namespace: vermeg
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: vermeg123
  POSTGRES_DB: vermeg_sirh
  POSTGRES_USER: vermeg
  POSTGRES_PASSWORD: vermeg123
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
