server:
  port: 8081

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/vermeg-sirh}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: employee-service
          uri: http://employee-service:8082
          predicates:
            - Path=/api/auth/**,/api/employees/**,/api/leaves/**,/api/documents/**,/api/salaries/**,/api/messages/**,/api/news/**,/api/notifications/**,/api/stats/**,/api/hr-admins/**,/api/departments/**,/api/positions/**,/api/users/**,/api/contract-types/**,/api/team/**
        - id: recruitment-service
          uri: http://recruitment-service:8083
          predicates:
            - Path=/api/recruitment/**,/api/public/jobs/**,/api/jobs/**,/api/applications/**,/api/interviews/**
        - id: approval-service
          uri: http://approval-service:8084
          predicates:
            - Path=/api/approvals/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
